-- Schema inicial de RetroRental.
--
-- Generado a partir de las entidades JPA (Hibernate ddl-auto=create sobre una DB
-- vacia, volcado con pg_dump --schema-only) y despues editado a mano para dar
-- nombres legibles a las constraints y agregar los indices/uniques que el modelo
-- necesita pero Hibernate no deriva solo.
--
-- A partir de aca el schema NO lo maneja Hibernate: ddl-auto es `validate` en
-- todos los perfiles. Todo cambio de estructura va en un archivo nuevo
-- (V2__..., V3__...), nunca editando este.

-- ---------------------------------------------------------------------------
-- personas (+ administradores / empleados)
--
-- Herencia JOINED: `personas` tiene los campos comunes y cada subtipo su propia
-- tabla, con el id como PK y FK a la vez.
-- ---------------------------------------------------------------------------

CREATE TABLE personas (
    id               integer                GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           character varying(255) NOT NULL,
    apellido         character varying(255) NOT NULL,
    documento        character varying(255) NOT NULL,
    username         character varying(255) NOT NULL,
    password         character varying(255) NOT NULL,
    rol              character varying(255) NOT NULL,
    codigo_area      character varying(5)   NOT NULL,
    telefono_numero  character varying(255),

    CONSTRAINT personas_rol_check
        CHECK (rol IN ('EMPLEADO', 'ADMINISTRADOR'))
);

-- Unicidad de identidad a nivel DB. AuthService ya chequea con existsBy* antes
-- de insertar, pero esa validacion es leer-despues-escribir: dos registros
-- concurrentes la pasan los dos y quedan duplicados. El constraint es la unica
-- garantia real.
ALTER TABLE personas ADD CONSTRAINT personas_username_key UNIQUE (username);
ALTER TABLE personas ADD CONSTRAINT personas_documento_key UNIQUE (documento);

CREATE TABLE administradores (
    id integer NOT NULL PRIMARY KEY,

    CONSTRAINT administradores_id_fkey
        FOREIGN KEY (id) REFERENCES personas (id)
);

CREATE TABLE empleados (
    id               integer NOT NULL PRIMARY KEY,
    fecha_alta       date    NOT NULL,
    fecha_baja       date,
    id_administrador integer,

    CONSTRAINT empleados_id_fkey
        FOREIGN KEY (id) REFERENCES personas (id),
    CONSTRAINT empleados_id_administrador_fkey
        FOREIGN KEY (id_administrador) REFERENCES administradores (id)
);

CREATE INDEX empleados_id_administrador_idx ON empleados (id_administrador);

-- ---------------------------------------------------------------------------
-- vehiculos
--
-- fecha_baja = baja logica. No se borran fisicamente porque los tickets los
-- referencian con FK NOT NULL.
-- id_operario = ultimo empleado que cargo (informativo: el parque es un pool
-- compartido, no una asignacion exclusiva).
-- ---------------------------------------------------------------------------

CREATE TABLE vehiculos (
    id                          integer                GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patente                     character varying(255) NOT NULL,
    tipo_vehiculo               character varying(255) NOT NULL,
    tipo_combustible            character varying(255) NOT NULL,
    estado                      character varying(255) NOT NULL,
    capacidad_tanque            integer                NOT NULL,
    kilometraje                 integer                NOT NULL,
    consumo_promedio            numeric(10,2)          NOT NULL,
    fecha_ultimo_mantenimiento  date                   NOT NULL,
    fecha_baja                  date,
    id_operario                 integer,

    CONSTRAINT vehiculos_patente_key UNIQUE (patente),
    CONSTRAINT vehiculos_id_operario_fkey
        FOREIGN KEY (id_operario) REFERENCES empleados (id),
    CONSTRAINT vehiculos_tipo_vehiculo_check
        CHECK (tipo_vehiculo IN ('MAQUINA', 'CAMIONETA', 'CAMION')),
    CONSTRAINT vehiculos_tipo_combustible_check
        CHECK (tipo_combustible IN ('NAFTA_SUPER', 'NAFTA_PREMIUM', 'GASOIL_GRADO_2', 'GASOIL_GRADO_3', 'GNC')),
    CONSTRAINT vehiculos_estado_check
        CHECK (estado IN ('DISPONIBLE', 'EN_USO', 'EN_MANTENIMIENTO'))
);

CREATE INDEX vehiculos_id_operario_idx ON vehiculos (id_operario);

-- Tabla puente del ManyToMany Administrador <-> Vehiculo.
CREATE TABLE administrador_vehiculo (
    id_administrador integer NOT NULL,
    id_vehiculo      integer NOT NULL,

    CONSTRAINT administrador_vehiculo_id_administrador_fkey
        FOREIGN KEY (id_administrador) REFERENCES administradores (id),
    CONSTRAINT administrador_vehiculo_id_vehiculo_fkey
        FOREIGN KEY (id_vehiculo) REFERENCES vehiculos (id)
);

-- ---------------------------------------------------------------------------
-- proveedores y precios
-- ---------------------------------------------------------------------------

CREATE TABLE proveedores (
    id        integer                GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    character varying(255) NOT NULL,
    cuit      character varying(255) NOT NULL,
    servicio  character varying(255) NOT NULL,

    CONSTRAINT proveedores_servicio_check
        CHECK (servicio IN ('COMBUSTIBLE', 'REPUESTOS', 'OTROS'))
);

-- Catalogo de precios con historia: fecha_hasta NULL = precio vigente.
-- tipo_combustible y proveedor_id son nullable porque solo aplican al servicio
-- COMBUSTIBLE (REPUESTOS/OTROS los dejan en null).
CREATE TABLE precios (
    id                integer                GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    precio_unitario   numeric(10,2)          NOT NULL,
    servicio          character varying(255) NOT NULL,
    tipo_combustible  character varying(255),
    proveedor_id      integer,
    fecha_desde       date                   NOT NULL,
    fecha_hasta       date,

    CONSTRAINT precios_proveedor_id_fkey
        FOREIGN KEY (proveedor_id) REFERENCES proveedores (id),
    CONSTRAINT precios_servicio_check
        CHECK (servicio IN ('COMBUSTIBLE', 'REPUESTOS', 'OTROS')),
    CONSTRAINT precios_tipo_combustible_check
        CHECK (tipo_combustible IN ('NAFTA_SUPER', 'NAFTA_PREMIUM', 'GASOIL_GRADO_2', 'GASOIL_GRADO_3', 'GNC'))
);

-- El formulario de carga busca el precio vigente por (proveedor, combustible):
-- es la consulta mas caliente del flujo de tickets.
CREATE INDEX precios_vigente_idx
    ON precios (proveedor_id, tipo_combustible)
    WHERE fecha_hasta IS NULL;

-- ---------------------------------------------------------------------------
-- tickets
-- ---------------------------------------------------------------------------

CREATE TABLE tickets (
    id                integer                     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    litros            double precision            NOT NULL,
    fecha_carga       timestamp(6) without time zone NOT NULL,
    ticket_foto_url   character varying(255),
    tablero_foto_url  character varying(255),
    id_persona        integer                     NOT NULL,
    id_vehiculo       integer                     NOT NULL,
    id_proveedor      integer                     NOT NULL,
    id_precio         integer                     NOT NULL,

    CONSTRAINT tickets_id_persona_fkey
        FOREIGN KEY (id_persona) REFERENCES personas (id),
    CONSTRAINT tickets_id_vehiculo_fkey
        FOREIGN KEY (id_vehiculo) REFERENCES vehiculos (id),
    CONSTRAINT tickets_id_proveedor_fkey
        FOREIGN KEY (id_proveedor) REFERENCES proveedores (id),
    CONSTRAINT tickets_id_precio_fkey
        FOREIGN KEY (id_precio) REFERENCES precios (id)
);

-- Los tres accesos reales a tickets: el historial del empleado (por persona),
-- el detalle por vehiculo, y las estadisticas del admin (por rango de fecha).
CREATE INDEX tickets_id_persona_idx  ON tickets (id_persona);
CREATE INDEX tickets_id_vehiculo_idx ON tickets (id_vehiculo);
CREATE INDEX tickets_fecha_carga_idx ON tickets (fecha_carga);
