-- ---------------------------------------------------------------------------
-- Herramientas (motosierra, bidones, etc.)
--
-- Una herramienta NO es un vehiculo: no tiene identificador/patente, modelo,
-- tipo de vehiculo, uso acumulado (no lleva contador ni horometro), consumo
-- promedio ni tipo de combustible fijo. Solo tiene nombre y capacidad. El
-- combustible se elige carga por carga (ver tickets mas abajo), por eso NO se
-- agrega un valor HERRAMIENTA al enum tipo_vehiculo de `vehiculos`: son dos
-- entidades distintas con reglas distintas, no una variante de la misma.
--
-- fecha_baja = baja logica, mismo patron que vehiculos.fecha_baja: no se borra
-- fisicamente porque los tickets la referencian.
-- ---------------------------------------------------------------------------

CREATE TABLE herramientas (
    id         integer                GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     character varying(255) NOT NULL,
    capacidad  numeric(10,2)          NOT NULL,
    fecha_baja date
);

-- ---------------------------------------------------------------------------
-- tickets: ahora puede pertenecer a UN vehiculo O a UNA herramienta, nunca los
-- dos ni ninguno. id_vehiculo deja de ser NOT NULL y se agrega id_herramienta.
-- El CHECK es la garantia real (a nivel service la exclusividad la valida
-- CreateTicketRequest, pero la constraint no depende de que el codigo la
-- respete).
-- ---------------------------------------------------------------------------

ALTER TABLE tickets ALTER COLUMN id_vehiculo DROP NOT NULL;

ALTER TABLE tickets ADD COLUMN id_herramienta integer;

ALTER TABLE tickets ADD CONSTRAINT tickets_id_herramienta_fkey
    FOREIGN KEY (id_herramienta) REFERENCES herramientas (id);

ALTER TABLE tickets ADD CONSTRAINT tickets_origen_check
    CHECK (
        (id_vehiculo IS NOT NULL AND id_herramienta IS NULL) OR
        (id_vehiculo IS NULL AND id_herramienta IS NOT NULL)
    );

CREATE INDEX tickets_id_herramienta_idx ON tickets (id_herramienta);

COMMENT ON COLUMN tickets.id_vehiculo IS
    'Vehiculo cargado. Exactamente uno de id_vehiculo/id_herramienta es NOT NULL (ver tickets_origen_check).';

COMMENT ON COLUMN tickets.id_herramienta IS
    'Herramienta cargada. Exactamente uno de id_vehiculo/id_herramienta es NOT NULL (ver tickets_origen_check).';

-- ---------------------------------------------------------------------------
-- precios.tipo_combustible: sumar MEZCLA (nafta con aceite, para la
-- motosierra). Solo en `precios`: un vehiculo nunca carga mezcla, asi que
-- vehiculos_tipo_combustible_check queda intacto a proposito.
-- ---------------------------------------------------------------------------

ALTER TABLE precios DROP CONSTRAINT precios_tipo_combustible_check;

ALTER TABLE precios ADD CONSTRAINT precios_tipo_combustible_check
    CHECK (tipo_combustible IN
        ('NAFTA_SUPER', 'NAFTA_PREMIUM', 'GASOIL_GRADO_2', 'GASOIL_GRADO_3', 'GNC', 'MEZCLA'));
