-- ---------------------------------------------------------------------------
-- Padron de empleados habilitados a registrarse.
--
-- Por que existe: /auth/register es publico a proposito (los empleados se dan
-- de alta solos desde la app, sin friccion). Sin un padron, "publico" significa
-- que CUALQUIER persona de internet que conozca la URL de la API obtiene una
-- cuenta EMPLEADO valida: lee el parque de vehiculos, toma unidades del pool,
-- crea tickets falsos que mueven el odometro y el consumo de vehiculos reales,
-- y consume el OCR pago.
--
-- Esta tabla es la lista de documentos que el administrador autoriza. El
-- registro sigue siendo self-service y el formulario del empleado NO cambia:
-- lo unico que se agrega es que el backend verifica que ese documento este en
-- el padron antes de crear la cuenta.
--
-- Por que una tabla aparte y no filas incompletas en `personas`: para admitir
-- un "documento habilitado pero todavia sin persona" habria que sacarle el
-- NOT NULL a nombre, apellido, username, password, rol y telefono, es decir a
-- toda la tabla de identidad. Y peor: /auth/register pasaria de "documento ya
-- existe -> rechazar SIEMPRE" a hacer un UPDATE condicional sobre una fila
-- existente, en el unico endpoint sin autenticar de la API. Un error en esa
-- condicion equivale a que un desconocido se apropie de la cuenta de un
-- empleado. La regla de register se mantiene deliberadamente trivial.
-- ---------------------------------------------------------------------------

CREATE TABLE empleados_habilitados (
    id         integer                GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento  character varying(255) NOT NULL,
    apellido   character varying(255) NOT NULL,
    nombre     character varying(255),
    fecha_alta date                   NOT NULL,
    fecha_uso  timestamp(6) without time zone,
    id_persona integer,

    -- Un documento se habilita una sola vez. Ademas de la regla de negocio,
    -- es la garantia real contra dos altas concurrentes del mismo documento
    -- (el service chequea antes de insertar, pero eso es leer-despues-escribir).
    CONSTRAINT empleados_habilitados_documento_key UNIQUE (documento),

    CONSTRAINT empleados_habilitados_id_persona_fkey
        FOREIGN KEY (id_persona) REFERENCES personas (id),

    -- "Usado" es un estado atomico: o hay fecha de uso Y persona, o no hay
    -- ninguna de las dos. Sin este CHECK se puede quedar una fila marcada como
    -- consumida sin saber quien la consumio, que es justo la trazabilidad por
    -- la que se guarda id_persona.
    CONSTRAINT empleados_habilitados_uso_check
        CHECK (
            (fecha_uso IS NULL     AND id_persona IS NULL) OR
            (fecha_uso IS NOT NULL AND id_persona IS NOT NULL)
        )
);

COMMENT ON TABLE empleados_habilitados IS
    'Documentos autorizados por el administrador a registrarse via /auth/register.';

COMMENT ON COLUMN empleados_habilitados.apellido IS
    'Se compara contra el apellido que escribe el empleado al registrarse, normalizado (sin acentos, sin distinguir mayusculas). Un documento filtrado solo no alcanza para registrarse.';

COMMENT ON COLUMN empleados_habilitados.nombre IS
    'Opcional. Referencia para que el administrador reconozca la fila en su lista; NO se valida contra el registro.';

COMMENT ON COLUMN empleados_habilitados.fecha_uso IS
    'Momento en que se consumio la habilitacion. NULL = habilitado, todavia sin registrar.';

COMMENT ON COLUMN empleados_habilitados.id_persona IS
    'Persona creada al consumir esta habilitacion. NULL mientras no se uso.';

CREATE INDEX empleados_habilitados_fecha_uso_idx ON empleados_habilitados (fecha_uso);
